### ISSUE TITLE
I press F2, nothing happens, what could be the problem?

### ISSUE THREAD

**Issue by Nascar22** [SlowsieNT/Genshin-Impact#3]
Hello, I tried to figure it out, but it doesn’t work out for me, I seem to be doing everything right, but when I press F2, nothing happens, what could be the problem? I changed the path to StandaloneWindows64, I run as administrator, fullscreen 1920x1080, I wanted to ask you in discord, but I could not find you

**Comment by SlowsieNT** [comment]
Apologies for the delay, didn't care to look into issues.

The `StandaloneWindows64` is used only for skipping **first** cutscene.
Fullscreen 1920x1080 is default setting, and should be working.

If the problem persists, please add me by that id above.
Thank you for the feedback.
