### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by realpritam** [SlowsieNT/Genshin-Impact#4]
Something like this for mobile too?

**Comment by SlowsieNT** [comment]
No appropriate tools were found to even attempt to achieve such feat.
Closest alternative is `Tasker` android app.
However there is no feature such as `silent screenshot`, which is main requirement to detect ui on user's screen.

Labelled as `no solution` (lack of appropriate tools), and any help is welcome.

Replication of `Retrier3` cannot be done, for now.

Not closing issue: may be possible in the future.

**Comment by realpritam** [comment]
> 

Try touch recorder macro clicker

**Comment by SlowsieNT** [comment]
> > 
> 
> Try touch recorder macro clicker

I just checked the suggested tool (`Touch Recorder (macro clicker)`).
The tool does not provide appropriate manual/documentation for **advanced scripting**.

Please understand that these functions are required to make this work:
```cs
// Hard requirement:
Bitmap scr = Screen.Capture(); // silently
int color = scr.GetPixel(x, y);

// Other - Hard requirement:
Keyboard.SendKeys();
Touch.Tap();
Touch.Hold();
Touch.Move();
// Soft requirement:
File.Write();
File.Read();
// Less relevant:
Touch.ZoomIn();
Touch.ZoomOut();

```
Without these functions I will not attempt writing "blind macro" as it will be more of a pain than less pain.

Screen capture (not record) may require device to be `rooted`, and the reason of this issue being marked as `no solution`
