### ISSUE TITLE
Miss

### ISSUE THREAD

**Issue by Densyeu** [SlowsieNT/Genshin-Impact#5]
[Player]; 1=yes, 0=no it should be 2
Female=0
Name=Aether

[Screen]
; WM1440=1440x900 WINDOWED MODE
; FS1920=1920x1080 FULL SCREEN
Resolution=FS1920

; INGAME
if (vPixelette["UIIGTwinSelect"]) {
	if (1 == vRID) {
		if (vPlayerFemale)
			ELClick2(vWinID, 419, 613, vWinX, vWinY, Delay:=111)
		else ELClick2(vWinID, 1507, 315, vWinX, vWinY, Delay:=111)
	}
	if (2 == vRID) {
		if (vPlayerFemale)
			ELClick2(vWinID, 334, 477, vWinX, vWinY, Delay:=111)
		else ELClick2(vWinID, 1112, 320, vWinX, vWinY, Delay:=111)
	}

**Comment by SlowsieNT** [comment]
Resolved.

**Comment by SlowsieNT** [comment]
> [Player]; 1=yes, 0=no it should be 2 Female=0 Name=Aether
> 
> [Screen] ; WM1440=1440x900 WINDOWED MODE ; FS1920=1920x1080 FULL SCREEN Resolution=FS1920
> 
> ; INGAME if (vPixelette["UIIGTwinSelect"]) { if (1 == vRID) { if (vPlayerFemale) ELClick2(vWinID, 419, 613, vWinX, vWinY, Delay:=111) else ELClick2(vWinID, 1507, 315, vWinX, vWinY, Delay:=111) } if (2 == vRID) { if (vPlayerFemale) ELClick2(vWinID, 334, 477, vWinX, vWinY, Delay:=111) else ELClick2(vWinID, 1112, 320, vWinX, vWinY, Delay:=111) }

By logic `0` is `no`, and `1` is `yes`, however some languages regard `-1` as `no`/`false`, or similar.
PS: Thanks for reporting the issue.

**Comment by SlowsieNT** [comment]
Related, the `IniStruct::GetValue` got adjustments, which previously caused the issue
As of July
